# Generated by Django 6.0.7 on 2026-07-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='<django.db.models.fields.CharField>.<django.db.models.fields.CharField>', max_length=50),
        ),
    ]
