# Generated by Django 6.0.7 on 2026-07-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_account_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
