# Generated by Django 6.0.7 on 2026-07-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='description',
        ),
        migrations.AddField(
            model_name='technology',
            name='description_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='technology',
            name='description_fr',
            field=models.TextField(default=''),
        ),
    ]
