# Generated by Django 6.0.7 on 2026-07-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_technology_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons/%y/%m/%d'),
        ),
    ]
