# Generated by Django 6.0.7 on 2026-07-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_technology_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
