# Generated by Django 6.0.7 on 2026-07-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_delete_technology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
