# Generated by Django 6.0.7 on 2026-08-11 08:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('color', models.CharField(choices=[('teal', 'Teal (défaut)'), ('amber', 'Ambre'), ('red', 'Rouge')], default='teal', max_length=10, verbose_name='couleur du tag')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='confirmé (double opt-in)')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='inscrit le')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='désinscrit le')),
            ],
            options={
                'verbose_name': 'abonné newsletter',
                'verbose_name_plural': 'abonnés newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('excerpt', models.CharField(blank=True, help_text='Résumé court affiché sur les cartes et sous le titre (.excerpt / .dek).', max_length=300, verbose_name='chapô')),
                ('content', models.TextField(help_text="Corps de l'article. Peut être écrit en Markdown si tu utilises django-markdownx / mistune côté rendu.", verbose_name='contenu')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/%Y/%m/', verbose_name='image de couverture')),
                ('cover_caption', models.CharField(blank=True, max_length=200, verbose_name="légende de l'image")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=10, verbose_name='statut')),
                ('is_featured', models.BooleanField(default=False, help_text="Affiché dans le grand encart du hero en page d'accueil.", verbose_name='mis en avant')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publié le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='nombre de vues')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.category', verbose_name='catégorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('is_approved', models.BooleanField(default=True, help_text='Passe à False pour mise en modération avant affichage publique.', verbose_name='approuvé')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='en réponse à')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='blog_articl_publish_308f23_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='blog_articl_status_57fc64_idx'),
        ),
    ]
