# Generated by Django 6.0.7 on 2026-08-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('subject', models.CharField(max_length=150, verbose_name='sujet')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='reçu le')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('email_sent', models.BooleanField(default=False, help_text="Passe à True si l'envoi via send_mail() a réussi.", verbose_name='e-mail de notification envoyé')),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
