# Generated by Django 6.0.7 on 2026-08-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('color', models.CharField(choices=[('teal', 'Teal (défaut)'), ('amber', 'Ambre'), ('red', 'Rouge')], default='teal', max_length=10, verbose_name='couleur du tag')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['name'],
            },
        ),
    ]
