# Generated by Django 6.0.7 on 2026-08-11 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token de confirmation'),
        ),
    ]
