# Generated by Django 6.0.7 on 2026-08-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newslettersubscriber_confirmation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
