# Generated by Django 6.0.7 on 2026-08-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_article_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='email_sent',
        ),
    ]
