from django.shortcuts import render


def index(request):
    context = {
        'technologies': [
            {'icon': "images/vmware-vsphere.png", 'title': "VMware vSphere", 'desc_fr': "Une plateforme de virtualisation puissante qui permet de créer, gérer et optimiser une infrastructure informatique virtuelle.",'desc_en': "A powerful virtualization platform that enables the creation, management, and optimization of a virtual IT infrastructure.",'link':"#", 'tags_fr':"Virtualisation - SDDC", 'tags_en':"Virtualization - SDDC"},
            {'icon': "images/vmware-vsan.png", 'title': "VMware vSAN", 'desc_fr': "Une solution de stockage, elle permet de regrouper les disques des serveurs physique pour former un espace de stockage distribué.",'desc_en': "A storage solution that aggregates the local disks of physical servers to create a distributed storage space.", 'link':"#", 'tags_fr':"Virtualisation - HCI", 'tags_en':"Virtualization - HCI"},
            {'icon': "images/vmware-nsx.png", 'title': "VMware NSX", 'desc_fr': "Une plateforme de virtualisation réseau qui permet de créer, gérer et sécuriser dynamiquement l’infrastructure réseau de votre datacenter.", 'desc_en': "A network virtualization platform that enables dynamic creation, management, and security of your datacenter network infrastructure.", 'link':"#", 'tags_fr':"Virtualisation - SDN", 'tags_en':"Virtualization - SDN"},
            {'icon': "images/docker.png", 'title': "Docker", 'desc_fr': "Docker permet d'exécuter des applications conteneurisées. Il simplifie leur déploiement et améliore la portabilité et la scalabilité.", 'desc_en': "Docker runs containerized applications.It simplifies deployment and improves portability and scalability.", 'link':"#", 'tags_fr':"Virtualisation - Conteneur", 'tags_en':"Virtualization - Container"},
            {'icon': "images/kubernetes.png", 'title': "Kubernetes",'d esc_fr': "Kubernetes permet d’automatiser le déploiement, la gestion, la mise à l’échelle et la disponibilité des applications conteneurisées.", 'desc_en': "Kubernetes automates the deployment, management, scaling, and availability of containerized applications.", 'link':"#", 'tags_fr':"Virtualisation - Automatisation - Conteneur ", 'tags_en':"Virtualization - Automation, Container"},
            { 'icon': "images/nginx.png", 'title': "Nginx", 'desc_fr': "Un serveur web qui permet de gérer les requêtes HTTP et de distribuer le trafic réseau. Il améliore la rapidité et la sécurité des applications web.", 'desc_en': "A high web server that handles HTTP requests and distributes network traffic. It improves the speed and security of web applications.", 'link':"#", 'tags_fr':"Serveur web - Équilibrage de Charge - Proxy Inverse  ", 'tags_en':"Web Server - Load Balancing - Reverse Proxy"},
            {'icon': "images/fortinet.png", 'title': "Fortigate", 'desc_fr': "Un pare-feu nouvelle génération (NGFW), conçue pour protéger l'infrastructure IT contre les cybermenaces.", 'desc_en': "A next-generation firewall (NGFW), designed to protect IT infrastructure against cyber threats.", 'link':"#", 'tags_fr':"Sécurité - NGFW", 'tags_en':"Security - NGFW"},
            {'icon': "images/fortiweb.png", 'title': "FortiWeb", 'desc_fr': "Un pare-feu applicatif web (WAF), conçu pour protéger les applications web et les API contre les cybermenaces.",'desc_en': "A Web Application Firewall (WAF), designed to protect web applications and APIs from cyber threats.", 'link':"https://www.fortinet.com/fr/products/web-application-firewall/fortiweb", 'tags_fr':"Sécurité - WAF", 'tags_en':"Security - WAF"},
            {'icon': "images/fortimail.png", 'title': "FortiMail", 'desc_fr': "Une solution de sécurité, conçue pour protéger les systèmes de messagerie contre le spam, les malwares et les menaces véhiculées par email.", 'desc_en': "An security solution designed to protect messaging systems against spam, malware, and advanced email-borne threats.", 'link':"#", 'tags_fr':"Sécurité - Passerelle de messagerie", 'tags_en':"Security - Mail Gateway"},
            {'icon': "images/zabbix.png", 'title': "ZABBIX", 'desc_fr': "Une solution de supervision pour surveiller en continu l’état de santé de vos systèmes, équipements réseau et services applicatifs.",'desc_en': "An open-source monitoring solution designed to continuously track the health of your systems, network devices, and application services.", 'link':"#", 'tags_fr':"Supervision - Alerte", 'tags_en':"Monitoring - Alert"},
            {'icon': "images/veeam.jpg", 'title': "VEEAM", 'desc_fr': "Une solution de protection des données, elle permet de sauvegarder, répliquer et restaurer rapidement vos systèmes en cas d’incident.", 'desc_en': "A data protection solution that enables you to back up, replicate, and quickly restore your systems in the event of an incident.", 'link':"#", 'tags_fr':"Protection - Sauvegarde", 'tags_en':"Protection - Backup"},
            {'icon': "images/ad.png", 'title': "Microsoft Active Directory", 'desc_fr': "Un service d’annuaire qui permet de centraliser la gestion des utilisateurs, des ordinateurs et des ressources au sein d’un réseau d’entreprise.", 'desc_en': "A directory service that centralizes the management of users, computers, and resources within an enterprise network.", 'link':"#", 'tags_fr':"Service d’annuaire", 'tags_en':"Directory service"},
            {'icon': "images/exchange.png", 'title': "Microsoft Exchange", 'desc_fr': "Une plateforme de messagerie conçue pour offrir une communication sécurisée, performante et centralisée au sein des entreprises.",'desc_en': "A email platform designed to provide secure, efficient, and centralized communication within businesses.",'link':"#", 'tags_fr':"Service de messagerie", 'tags_en':"Messaging service"},
            {'icon': "images/sharepoint.png", 'title': "Microsoft SharePoint", 'desc_fr': "Une plateforme collaborative conçue pour centraliser l'information, fluidifier la communication interne et faciliter le travail en équipe.",'desc_en': "A collaborative platform designed to centralize information, streamline internal communication, and facilitate teamwork.",'link':"#", 'tags_fr':"Service collaboratif", 'tags_en':"Collaborative service"},
        ],
        'certifications': [ 
            {'icon': "images/vcp-dcv.png", 'title_fr': "VMware Certified Professional - Data Center Virtualization", 'title_en': "VMware Certified Professional - Data Center Virtualization", 'desc_fr': "Cette certification valide que je peux mettre en œuvre, gérer et dépanner une infrastructure vSphere, en utilisant les meilleures pratiques pour fournir une base puissante, flexible et sécurisée pour l'agilité commerciale qui peut accélérer la transformation vers le cloud computing.", 'desc_en': "This certification validates my ability to implement, manage, and troubleshoot a vSphere infrastructure, using best practices to provide a powerful, flexible, and secure foundation for business agility that can accelerate the transformation to cloud computing.", 'cert_url':"https://cp.certmetrics.com/vmware/en/public/verify/credential/5fbd473a41144071a71f249fd17191d5", 'organization':"VMware",},
            {'icon': "images/vsan-specialist.png", 'title_fr': "VMware Certified Specialist - vSAN", 'title_en': "VMware Certified Specialist - vSAN", 'desc_fr': "Cette certification confirme mon expertise technique sur VMware vSAN. Elle valide ma capacité à comprendre son architecture et ses fonctionnalités, à concevoir et déployer une infrastructure vSAN. ainsi qu’à administrer et exploiter efficacement un cluster vSAN.", 'desc_en': "This certification confirms my technical expertise on VMware vSAN. It validates my ability to understand its vSAN architecture and its functionalities, to design and deploy a vSAN infrastructure, as well as to effectively administer and operate a vSAN cluster.", 'cert_url':"https://www.credly.com/badges/31e784ea-5f05-406a-85a2-59984374593e", 'organization':"VMware"},
            {'icon': "images/vcp-nv.jpeg", 'title_fr': "VMware Certified Professional - Network Virtualization", 'title_en': "VMware Certified Professional - Network Virtualization", 'desc_fr': "Cette certification atteste de ma capacité à optimiser et transformer les opérations réseau et la sécurité informatique au sein de l’entreprise. Elle reconnaît mes compétences dans le déploiement, la configuration et la gestion de solutions de virtualisation réseau basées sur VMware NSX.", 'desc_en': "This certification validates my ability to optimize and transform network operations and IT security within the enterprise. It recognizes my expertise in deploying, configuring, and managing network virtualization solutions based on VMware NSX.", 'cert_url':"https://cp.certmetrics.com/vmware/en/public/verify/credential/f8588ad4c9c148b7bf992e5cd71a3dc7", 'organization':"VMware",},
            {'icon': "images/ummto.png", 'title_fr': "Master en Réseaux, Mobilités et Systèmes Embarqués", 'title_en': "Master’s Degree in Networks, Mobility, and Embedded Systems", 'desc_fr': "J'ai acquis une solide expérience théorique et pratique à travers différents modules tels que l'architecture des systèmes embarqués, la programmation parallèle, les réseaux et leur sécurité, le développement mobile, la virtualisation, et bien plus encore.", 'desc_en': "I gained solid theoretical and practical experience through various modules such as embedded systems architecture, parallel programming, networking and security, mobile development, virtualization, and much more.", 'link':"#", 'organization':"UMMTO",},
            {'icon': "images/ummto.png", 'title_fr': "Licence en Informatique", 'title_en': "Bachelor’s Degree in Computer Science", 'desc_fr': "J'ai appris à coder, à gérer des bases de données et à comprendre les réseaux, la sécurité informatique et les systèmes. Cette formation m'a donné de solides bases dans plusieurs domaines de l'informatique et m'a aidé à m'adapter aux nouvelles technologies.", 'desc_en': "I learned how to code, manage databases, and understand networks, cybersecurity, and systems. This training provided me with a strong foundation in several areas of IT and helped me adapt to new technologies.", 'link':"#", 'organization':"UMMTO",}
        ]
    }
    return render(request, 'pages/index.html', context)

def about(request):
    return render(request, 'pages/about.html')