# Generated by Django 6.0.7 on 2026-07-31 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
