# Generated by Django 6.0.7 on 2026-07-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytests', '0002_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
