# Generated by Django 6.0.7 on 2026-08-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytests', '0002_alter_car_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
