# Generated by Django 6.0.7 on 2026-08-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytests', '0003_alter_car_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='date',
            new_name='added',
        ),
    ]
