# Generated by Django 6.0.7 on 2026-08-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytests', '0004_rename_date_car_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'Car List'},
        ),
    ]
